Repository Dev-FE-3/toy-project2-team4, pull requests merged in 2025-03, with the labels that each got.

#26 Feat/class calendar
  app/(home)/(components)/addClassModal.jsx
  app/(home)/(components)/calendar.jsx
  app/(home)/(components)/calendarDate.jsx
  app/(home)/(components)/classItem.jsx
  app/(home)/(components)/classList.jsx
  app/(home)/(components)/day.jsx
  app/(home)/classData.jsx
  app/(home)/constants.jsx
  app/(home)/page.jsx
  app/(home)/page.module.scss
  app/page.js
  components/common/input/input.jsx
  components/common/input/input.module.scss
Labels: 🌴 style, 🚀 feat

#15 Feature/common button
  components/common/button/button.jsx
  components/common/button/button.module.scss
Labels: 🌴 style

#16 Feature/common dropdown
  app/modificationHistory/page.jsx
  components/common/dropdown/dropdown.jsx
  components/common/dropdown/dropdown.module.scss
Labels: 🚀 feat

#27 feat:로그인/회원가입 기능 구현
  app/login/components/loginForm.jsx
  app/login/components/signupForm.jsx
  app/login/page.jsx
  app/login/page.module.scss
  app/login/style/loginForm.module.scss
  app/login/style/signupForm.module.scss
  public/assets/loginimg.png
  styles/global.css
Labels: 🌴 style, 🚀 feat

#24 Feature/modification history
  app/modificationHistory/(components)/modificationHistory.jsx
  app/modificationHistory/(components)/modificationList.jsx
  app/modificationHistory/modificationHistory.module.scss
  app/modificationHistory/page.jsx
Labels: 🌴 style, 🚀 feat

#30 Feat/payment history list
  app/layout.jsx
  app/paymentHistory/data.js
  app/paymentHistory/page.jsx
  app/paymentHistory/paymentHistory.module.scss
  components/centeredLayout/centeredLayout.jsx
  components/centeredLayout/centeredLayout.module.scss
  components/navigation/navigation.jsx
  components/navigation/navigation.module.scss
  components/paymentHistory/index.js
  components/paymentHistory/paymentHistoryDetail/paymentHistoryDetail.jsx
  components/paymentHistory/paymentHistoryDetail/paymentHistoryDetail.module.scss
  components/paymentHistory/paymentHistoryList/paymentHistoryList.jsx
  components/paymentHistory/paymentHistoryList/paymentHistoryList.module.scss
  package-lock.json
  package.json
  public/images/mock_paymentHistory.webp
  utils/apiUtils.js
  utils/init.txt
  utils/timeUtils.js
Labels: 🚀 feat

#35 Commen componont
  components/common/button/button.jsx
  components/common/dropdown/dropdown.jsx
  components/common/dropdown/dropdown.module.scss
Labels: 🔨 refactor, 🌴 style

#43 feat:로그인 후 유저 정보 상태 관리(redux 세팅)
  app/login/page.jsx
  components/login/loginForm/loginForm.jsx
  components/login/loginForm/loginForm.module.scss
  components/login/signupForm/signupForm.jsx
  components/login/signupForm/signupForm.module.scss
  components/navigation/navigation.jsx
  store/reducers/authReducer.js
Labels: 🚀 feat

#49 refactor : 로그인 페이지 스타일 조정 및 네비게이션/layout.jsx 수정
  app/layout.jsx
  app/login/page.jsx
  app/login/page.module.scss
  components/login/loginForm/loginForm.jsx
  components/login/loginForm/loginForm.module.scss
  components/login/loginPageForm.module.scss
  components/login/signupForm/signupForm.jsx
  components/login/signupForm/signupForm.module.scss
  components/navigation/navigation.jsx
  components/navigation/navigation.module.scss
  components/protectedroute/protectedroute.jsx
Labels: 🔨 refactor, 🌴 style, 🚀 feat

#52 Style/navigation phs
  app/favicon.ico
  app/layout.jsx
  components/navigation/navigation.jsx
  components/navigation/navigation.module.scss
  public/images/title-logo.svg
Labels: 🌴 style

#54 Feat/class calendar
  app/(home)/(components)/calendar.jsx
  app/(home)/(components)/classList.jsx
  app/(home)/(components)/day.jsx
  app/(home)/classData.js
  app/(home)/constants.js
  app/(home)/page.jsx
  app/(home)/page.module.scss
  components/classCalendar/addClassModal/addClassModal.jsx
  components/classCalendar/addClassModal/addClassModal.module.scss
  components/classCalendar/calendarDate/calendarDate.jsx
  components/classCalendar/calendarDate/calendarDate.module.scss
  components/classCalendar/calendarHeader/calendarHeader.jsx
  components/classCalendar/calendarHeader/calendarHeader.module.scss
  components/classCalendar/classItem/classItem.jsx
  components/classCalendar/classItem/classItem.module.scss
  components/classCalendar/day/day.jsx
  components/classCalendar/day/day.module.scss
  components/classCalendar/index.js
  components/common/input/input.jsx
  mocks/data/classCalendarData.json
  mocks/handlers.js
  store/reducers/actionsType.js
  store/reducers/calendarReducer.js
  store/reducers/classCalendarReducer/classCalendarActions.js
  store/reducers/classCalendarReducer/classCalendarReducer.js
  store/rootReducer.js
Labels: 🔨 refactor, 🌴 style

#65 Refactor/class calendar
  components/classCalendar/calendarHeader/calendarHeader.jsx
  components/classCalendar/classItem/classItem.jsx
  components/classCalendar/day/day.jsx
Labels: 🔨 refactor
